# Generated by Django 5.0 on 2024-02-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0003_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
