# Generated by Django 5.0 on 2024-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0006_enrollment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='url',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.TextField(default='https://freedesignfile.com/upload/2022/10/Young-people-learning-English-illustration-vector.jpg'),
        ),
    ]
